# Generated by Django 5.1.4 on 2024-12-10 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('base_price', models.FloatField()),
                ('discount_rate', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_prices', to='cars.car')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_prices', to='cars.currency')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.company'),
        ),
        migrations.CreateModel(
            name='CarLocalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_price', models.FloatField()),
                ('exchange_rate', models.FloatField()),
                ('car_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_local_prices', to='cars.carprice')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_local_prices', to='cars.currency')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.FloatField()),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='cars.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='cars.currency')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_from_location', to='cars.location'),
        ),
        migrations.AddField(
            model_name='car',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_to_location', to='cars.location'),
        ),
        migrations.CreateModel(
            name='RentalAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('pricing_unit', models.CharField(max_length=255)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_addons', to='cars.currency')),
            ],
        ),
        migrations.CreateModel(
            name='RentalAddonLocalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_price', models.FloatField()),
                ('exchange_rate', models.FloatField()),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_addon_local_prices', to='cars.rentaladdon')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_addon_local_prices', to='cars.currency')),
            ],
        ),
        migrations.CreateModel(
            name='RentalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('addons', models.ManyToManyField(related_name='rental_packages', to='cars.rentaladdon')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rental_packages', to='cars.car')),
            ],
        ),
    ]
